### ISSUE TITLE
Importing petsc4py

### ISSUE THREAD

**Issue by DavideBaroliUniLu** [hippylib/hippylib#1]
As enhancement with respect to use cpp compiled extension, you can use directly in python the 
functionality of petsc library with petsc4py.

**Comment by hippylib-admin** [comment]
Ciao Davide,

I agree with you that using petsc4py instead of cpp compiled extension would make the code shorter and easier to read.

Unfortunately, the pre-compiled FEniCS binaries for MacOS 10.10 and 10.11 (https://fenicsproject.org/download/osx_details.html) do not include petsc4py.

The FEniCS community has now switched to Docker (as a way to support MacOS/Win) and they will not distribute pre-compiled FEniCS binaries for newer releases of FEniCS.

We will definitely introduce petsc4py inside hIPPYlib once we are ready to move away from the MacOS pre-compiled FEniCS binaries.

Thanks!

Umberto

**Comment by uvilla** [comment]
We finally addressed this issue during the refactoring of hIPPYlib to support FEniCS 2019.1
