### ISSUE TITLE
Generalized parRandom

### ISSUE THREAD

**Issue by eldarkh** [hippylib/hippylib#20]
I have extended the `parRandom` machinery to allow for general Gaussian distributions (vector means and full covariances) for some of the Exxon related work, if this might be of interest for general use I can create a PR with my changes and extra tests.

The user interface changes slightly: `normal(mu, sigma, out=None)`. The only questionable part is that it the implementation I have currently requires `sigma^(1/2)` as a matrix to be passed as an argument.

**Comment by uvilla** [comment]
@eldarkh,

Is not this already taken care of by the finite dimensional Gaussian prior class in this [PR](https://github.com/hippylib/hippylib/pull/7)?

If `out` is distributed then `sigma^(1/2)` must also be a distributed parallel matrix, and not local one.
I think it is too complicated to handle this case inside parRandom, one may be better off to write a small function/class that uses `parRandom` to achieve this goal.

**Comment by eldarkh** [comment]
@uvilla I don't think it is done in the PR you linked, but I completely agree with the rest of your comment, will keep it for local Exxon use then

**Comment by joshuawchen** [comment]
@siddhantwahal  I like the idea of an abstract `probability_distribution`.

**Comment by joshuawchen** [comment]
Along the same lines, I also like the idea of a general `GaussianDistribution` class, which inherits from `ProbabilityDistribution`. Most of our current priors would derive from `GaussianDistribution`. This would also preview a potential future of other types of `ProbabilityDistribution`s, if we do introduce others, such as Besov, or anything else.

**Comment by siddhantwahal** [comment]
@uvilla if you think that's a feasible direction to proceed in the future, I can open a new issue for this.

**Comment by joshuawchen** [comment]
@siddhantwahal if you start this issue- my thought is that a Gaussian has as properties the mean function, covariance operator and perhaps  precisian operator, all as properties. The majority of the Gaussians we have now then are special cases with a particular covariance operator.

**Comment by uvilla** [comment]
@siddhantwahal , @joshuawchen , @eldarkh ,

I think that code generalization should move at the same pace as features we want to add to hIPPYlib.
E.g., if there is no current need for a `ProbabilityDistribution` outside using it as prior, I would not just yet create a new superclass that only has one concrete implementation.

On the other hand, we should definitely involve @AIlona in the discussion, since she is working both in the deterministic framework by adding support for non-quadratic regularizations (Total Variation and Vector Total Variation), and in the Bayesian one by adding non-Gaussian priors like the Gaussian-TV prior.

**Comment by joshuawchen** [comment]
Wouldn't it be best for a prior to inherit from a `ProbabilityDistribution` rather than from a `Regularization`? A prior then gets interpreted as a regularization through its `- log `. This is somehow, somewhat, philosophical. Whether to think about things mainly in terms of deterministic problems or probabilistic ones. Since hippylib is building up to be more about Bayesian inference than deterministic inversion for the MAP point now, it seems language and classes that emphasize Probability Distributions is clearer.

**Comment by eldarkh** [comment]
Having `Regularization` might allow for entities like TV which is not a prior but is a regularization. Also, I think methods like `cost` indicate `Regularization` nature of priors (statistical distributions do not have such notions). So maybe proper priors are just `Regularization` classes implemented in terms of `ProbabilityDistribution` objects? So both abstractions are needed, but rather than for priors to inherit from `ProbDistr` we will do composition there, so `ProbDistr` is an attribute of a prior. Just my 2cents.

**Comment by joshuawchen** [comment]
So a `Prior` is a `Regularization` which also has a notion of it being a `ProbabilityDistribution`. In this sense, while other `Regularizations` would not need to be associated to a `ProbabilityDistribution`. The probability distribution aspects related to sampling, while the while the regularization aspects related to cost/gradient/hessian, but do not need the concept of being able to sample from it. 

If this is the general idea, I think multiple inheritance makes the most sense   

   Regularization       ProbabilityDistribution
                    \            /
                       Prior

**Comment by AIlona** [comment]
Yes, I also think that `Regularization` and `ProbabilityDistribution` should both be present and, in particular, used in the implementation of priors either using multiple inheritance or composition.
