### ISSUE TITLE
hippylib fork for Firedrake

### ISSUE THREAD

**Issue by joshuawchen** [hippylib/hippylib#26]
Its been a longstanding goal for hippylib to consider moving over to firedrake. One idea is to create a fork of hippylib that starts moving things over to firedrake.

**Comment by eldarkh** [comment]
I am curious if there is a way to have support for both simultaneously? Might sound dumb, but since a lot of things in firedrake and fenics have same interfaces, I am genuinely curious if we could get away with `try/excepts` and if so, how many of these we would need.

**Comment by AIlona** [comment]
Does anyone know anything about Fenics-HPC and if it can be of any interest?

**Comment by joshuawchen** [comment]
I like the idea of try/excepts to get away with one interface for now. it would be great if we all started out by just installing firedrake, and just seeing what breaks, and incrementally fixing things in this experimental branch

**Comment by joshuawchen** [comment]
> Genuinely curious, what advantage does firedrake have over fenics?

It seems, from various people's scaling tests, firedrake scales very well, while Fenics does not. 
Lets see if we can find sources for this and post them here?

**Comment by joshuawchen** [comment]
https://www.semanticscholar.org/paper/Firedrake%3A-Automating-the-Finite-Element-Method-by-Rathgeber-Ham/04eee2aa4166a52a9773acfa74ec3aa8e3e635fb/figure/2

This seems to show modest, but definitely better performance from Firedrake most of the time. Particularly, for assembly, which would be a big deal for us.

**Comment by alexanderzimmerman** [comment]
Another big difference between FEniCS and Firedrake is that Firedrake tries to expose PETSc as much as possible. For example I think it's supposed to be much easier to compose block preconditioners in Firedrake.

I think I did a poor job answering Omar's question yesterday about how easy it is to move from FEniCS to Firedrake. At least for my own work, I found it trivial. Of course they don't both support all of the same things, so if you're using any of the more esoteric features of FEniCS, then maybe they aren't supported. In my own case, I could only use Firedrake once I was no longer relying on FEniCS's built-in adaptive mesh refinement.

**Comment by alexanderzimmerman** [comment]
> I am curious if there is a way to have support for both simultaneously? Might sound dumb, but since a lot of things in firedrake and fenics have same interfaces (at least from what I know), I am genuinely curious if we could get away with `try/excepts` and if so, how many of these we would need.

Based on my interactions with the FEniCS and Firedrake communities so far, I would expect them to diverge more over time. Has anyone here gone to the annual FEniCS conference yet? I went to the 2018 conference and it really helped shaped my vision about where UFL, FEniCS, FEniCS-HPC, and Firedrake are going. The next one is in June in D.C.: https://fenicsproject.org/fenics19/

**Comment by alexanderzimmerman** [comment]
> @alexanderzimmerman I think you talking about [pyadjoint](https://bitbucket.org/dolfin-adjoint/pyadjoint/src/master/)

Yep that one!

**Comment by alexanderzimmerman** [comment]
> Does anyone know anything about Fenics-HPC and if it can be of any interest?

I haven't used FEniCS-HPC; but I met some of the developers at the FEniCS conference and have since been in touch with Johan Jannson, exploring whether I wanted to use it for my forward simulations.

FEniCS-HPC branched off from FEniCS several years ago; but they still interact and go to the same FEniCS conference, as do the Firedrake people (though Firedrake also has an annual workshop that I haven't attended yet).

One huge difference is that FEniCS-HPC doesn't have a Python interface, bur rather just C++.

Johan Jansson teaches [a MOOC for FEM in HPC](http://www.csc.kth.se/~jjan/index.php/mooc-hpfem/) which they just started a year ago. It could have changed by now; but the first course uses FEniCS and then the second course uses FEniCS-HPC.

Also they're setting up [a web service](http://mso4sc.eu/).

A big contribution from FEniCS-HPC is their scalable adaptive mesh refinement with dynamic load balancing. They have some really impressive results for full aircraft.
