### ISSUE TITLE
fenics 2016.1.0 & paper?

### ISSUE THREAD

**Issue by ldong87** [hippylib/hippylib#3]
Hi,

I think this software is a pretty good trial to make UQ analysis relatively accessible to more researchers. Thanks for open-sourcing it. I have a couple questions / suggestions. Since my membership to your google group is pending for quite some time, I'll just post my questions here.

1. Now that fenics has updated to 2016.1.0 for quite some time, have you tested hippylib on that version? Have you considered when to release a hippylib that is compatible to the latest fenics?

2. I don't seem to be able to locate a proper paper that describes the detailed validation and verification of the hippylib. Is there any or are they still under review? Otherwise, is the only citable source the hippylib website, i.e.
@article{VillaPetraGhattas2016,
title = {"hIPPYlib: AN EXTENSIBLE SOFTWARE FRAMEWORK FOR LARGE-SCALE DETERMINISTIC AND LINEARIZED BAYESIAN INVERSION"},
author = {Villa U., and Petra, N., and Ghattas, O.},
year = {2016},
url = {http://hippylib.github.io}
}?

Thanks,
Li

**Comment by hippylib-admin** [comment]
Hi Li,

Thanks for your message.
My apologies that I have not check to google groups in a while. I will take car of it ASAP.

1. The main reason why we have not updated hippylib to FEniCS 2016.1 is because FEniCS 2016.1 introduces some interface changes that make cumbersome to support both versions (1.6 and 2016.1).
Our testing/developing platform is MacOS, and FEniCS 1.6 is the last version of FEniCS for which a pre-built binaries are provided. This is the main issue that is slowing down our transition to more recents version of FEniCS.
(NOTE: if you are using Docker is relative simple to pull old release of FEniCS, see https://github.com/hippylib/hippylib/issues/2)

2. We are still working on a manuscript describing hIPPYlib algorithms and functionalities. When the manuscript will be ready to be submitted, we will also upload the pre-print on arxiv.org. For now, we would really appreciate if you could cite hippylib using the website.

Best regards,

Umberto

**Comment by ldong87** [comment]
Hi Umberto,

Thanks for your quick reply. 

I'm actually compiling fenics from source so that I can use it on our school's cluster. Another quick question, if hippylib is developed and tested on MacOS, is hippylib working in parallel, such as MPI or openMP?

Thanks,
Li

**Comment by hippylib-admin** [comment]
Hi Li,

Some of the hIPPYlib functionalites work already in parallel (such as sampling from the prior distribution, and computing the MAP point using the Inexact Newton CG algorithm).
The randomized eigensolvers (singlePass, doublePass, singlePassG, and doublePassG) and the computation of traces and marginal variances are only serial.

A parallel implementation of the above functionalities is under development.

Best,

Umbe

**Comment by quang-ha** [comment]
I am happy to help out the transitioning to 2016.1.0 (soon to be 2016.2.0) if I can get on the boat.

**Comment by hippylib-admin** [comment]
Hi @quang-ha ,

Thank you for your offer!
If you would like to send us a patch we will be happy to include it in our next release.
However, please note that our biggest priority is to maintain backward compatibility with FEniCS 1.6.

Best,

Umbe

**Comment by hippylib-admin** [comment]
Hi @ldong87 ,

We have added partial support for `FEniCS 2016.1`.

All the examples in the `applications` and `tutorial` folder work as expected with both `FEniCS 1.6` and `FEniCS 2016.1`.

You can download the latest version of hippylib [here](https://goo.gl/pDb10B).

Best,

Umberto

**Comment by ldong87** [comment]
Thanks, Umberto! I'll try it soon.

Best,
Li


*Ph.D. candidate*
*Scientific Computation Research Center*
*Rensselaer Polytechnic Institute*
*http://www.rpi.edu/~dongl3/ <http://www.rpi.edu/~dongl3/>*
