### ISSUE TITLE
Define a `__version__`

### ISSUE THREAD

**Issue by Carreau** [hippylib/hippylib#9]
Would you be willing to add a `__version__` attribute in `__init__.py` ? That would allow dynamic checking of version ? 

Also have you considered to package using [flit](https://flit.readthedocs.io/en/latest/), or `setup.py` to make it easier to install instead of mounting CWD in a docker image ?

**Comment by eldarkh** [comment]
@Carreau Thank you for pointing this out, adding `__version__` would indeed allow for a standardized way of checking of version. 

I am currently looking into packaging the library in a more conventional way (via `setup.py`, hopefully it will be done soon), but thank you for the suggestion about flit, I have not heard of it, so will definitely take a look.

**Comment by uvilla** [comment]
Hi @Carreau ,

Thank you very much for your interest in `hIPPYlib`.

Of course, I can add the `__version__` attribute to the `__init__.py`.
The only thing I'm unsure is how to handle versioning in the master branch. That is, what should be the version number of the current master given that the latest release is `2.1.1`?
I'm thinking`2.1.1.next`, but maybe there are other options.

I'd also be happy if you and @eldarkh would like to contribute a `setup.py`.

My only requirements are:
-  to have a *developer friendly* `setup.py`, which also allows for *local* installations (i.e. if it gives the option not to copy the hippylib source files in the pythonpath).
- not to introduce additional dependencies because of the install script.

Bonus features of the `setup.py` script that I would appreciate are:
- Checking the fenics installation, and its dependencies (`petsc`, `slepc`, `hypre`, `ml`, `suitsparse`, `superludist`, `mumps`, etc).
- Checking the availability of other required python packages such as `mpi4py`, `numpy`, `scipy`, `matplotlib`, `petsc4py`.
- Precompile  the `cpp`  files in `hippylib`

Thank you to both you and @eldarkh  in advance!

Cheers,

Umberto

**Comment by uvilla** [comment]
Btw @Carreau , do you work with/know @npetra at UC Merced?

**Comment by Carreau** [comment]
> I'm thinking`2.1.1.next`, but maybe there are other options.

I would suggest following the Python [standard](https://www.python.org/dev/peps/pep-0440/), 
that is to say use `.dev`; it is understood by tools like pip as being "alway more up to date" and to "always reinstall". 

At least make sure the version is ["cannonical"](https://www.python.org/dev/peps/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions), or you get some funky business where pip get version number mixed-up.

> My only requirements are:
> to have a developer friendly setup.py, which also allows for local installations (i.e. if it gives the option not to copy the hippylib source files in the pythonpath).
> not to introduce additional dependencies because of the install script.

That's one of the thing [pyproject.toml](https://www.python.org/dev/peps/pep-0518/)/[flit](https://flit.readthedocs.io/en/latest/)/[poetry](https://poetry.eustace.io/) try to solve, but still need some work upstream in Python.

Usually you should not invoke `setup.py` directly, you should use `pip install . ` (`pip install -e .` if you want a dev install).  

> Bonus features of the setup.py script that I would appreciate are: [...]

Usually you probably also want to avoid relying too heavily on setup.py being executed on the user machine. It makes it harder to create Python wheels.

That's where conda shines, and where having a recipe on conda-forge https://github.com/conda-forge/  would make all these issues disappear for people using conda. 

> Btw @Carreau , do you work with/know @npetra at UC Merced?

Yes I know @npetra and ended up here by helping install hippylib on the Merced Cluster.

**Comment by uvilla** [comment]
@Carreau ,

Thank you for your feedback.
All of this is great. 
On the one hand, it will be very nice to have hippylib in conda-forge, since fenics is already there.
On the other hand, using conda is like using a hammer to kill a fly. `hIPPYlib` is a relatively simple package to "install". It is pure python or just-in-time compile cpp and therefore basically requires no installation if a working installation of FEniCS is available...

What worries me about pip/anaconda is the additional level of complexity to create releases and maintain the conda/pip packaging scripts.

I'll be happy to explore these options if there is a volunteer...

**Comment by Carreau** [comment]
> if a working installation of FEniCS is available

Well, but at least you will have no issues installing it ! At least on my new laptop it was pretty straitforward today. 

> What worries me about pip/anaconda is the additional level of complexity to create releases and maintain the conda/pip packaging scripts.

That's easier than it looks. The worse part for the package I maintain is actually updating the version number and changelog (also waiting for CI to build the package).

**Comment by uvilla** [comment]
@joshuawchen ,

I thought you may also be interested in this.

**Comment by joshuawchen** [comment]
Yes, I saw this. @Carreau, I’m very interested in this, and would find it useful.

**Comment by uvilla** [comment]
@Carreau,
Pull request #11 should partially address your comments.
We are also considering looking in `conda` in more details.

Please let us know what do you think. 

Thank you in advance.
